name: Terraform CI

on:
  push:
    branches:
      - "feature/**"  # run on code pushed to any feature branch
  pull_request:
    branches:
      - main  # run on pull requests to the main branch

jobs:
  terraform-ci:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: infra

    steps:
      # Pull the repository code onto the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install and configure the Terraform CLI on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Check Azure Account
        shell: powershell
        run: |
          az account show

      # Check .tf files are formatted correctly
      - name: Terraform Format Check
        run: terraform fmt -check
      
      - name: Diagnose Terraform Executables
        shell: powershell
        run: |
          Write-Host "=== setup-terraform executable ==="
          Get-Item "$env:TERRAFORM_CLI_PATH\terraform" | Format-List FullName,Length,LastWriteTime

          Write-Host "`n=== setup-terraform version ==="
          & "$env:TERRAFORM_CLI_PATH\terraform" version
          Write-Host "Exit code: $LASTEXITCODE"

          Write-Host "`n=== Local Terraform executable ==="
          Get-Item "C:\Software\terraform\terraform.exe" | Format-List FullName,Length,LastWriteTime

          Write-Host "`n=== Local Terraform version ==="
          & "C:\Software\terraform\terraform.exe" version
          Write-Host "Exit code: $LASTEXITCODE"

      # Prepare Terraform working directory and download required providers/modules
      - name: Terraform Init
        run: terraform init

      # Check whether Terraform configuration is valid
      - name: Terraform Validate
        run: terraform validate
