name: Terraform CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  terraform-ci:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Debug Azure environment
        shell: powershell
        run: |
          Write-Host "=== Azure CLI ==="
          az account show
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Azure CLI is NOT logged in"
            $global:LASTEXITCODE = 0
          }

          Write-Host "=== Relevant environment variable names ==="
          Get-ChildItem Env: |
            Where-Object {
             $_.Name -match "^(ARM_|AZURE_|ACTIONS_|GITHUB_)"
          } |
          Select-Object Name

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
