name: Terraform CI

on:
  push:
    branches:
      - "feature/**"  # run on code pushed to any feature branch
  pull_request:
    branches:
      - main  # run on pull requests to the main branch

jobs:
  terraform-ci:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: infra

    steps:
      # Pull the repository code onto the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install and configure the Terraform CLI on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false    # Disable the Terraform wrapper script to use Terraform CLI directly
      
      - name: Check Azure Account
        shell: powershell
        run: |
          az account show

      # Check .tf files are formatted correctly
      - name: Terraform Format Check
        run: terraform fmt -check

      # Prepare Terraform working directory and download required providers/modules
      - name: Terraform Init
        run: terraform init

      # Check whether Terraform configuration is valid
      - name: Terraform Validate
        run: terraform validate

      # TFLint - Terraform static analysis and code quality checks
      - name: Setup TFLint 
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version_file: .tool-versions

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --format compact